include: package:very_good_analysis/analysis_options.3.0.1.yaml

analyzer:
  exclude:
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
  errors:
    # required by freezed
    invalid_annotation_target: ignore